### ISSUE TITLE
-lm value required for Makefile on ubuntu

### ISSUE THREAD

**Issue by dvincentwest** [usnistgov/SCATMECH#1]
Sweet library, thanks very much.  In order to compile your example programs, I need to add -lm to the $(LIBRARIES) variable in the makefile

This is on Ubuntu 19.04, using gcc version 8.3.0

**Comment by thomas-germer** [comment]
Thank you for using SCATMECH and for pointing this issue out. I have pushed an update adding -lm to the LIBRARIES variable in the Makefile.
