### ISSUE TITLE
erf and tgamma function

### ISSUE THREAD

**Issue by jxo** [usnistgov/SCATMECH#3]
erf and tgamma function is not found
sizedistribution.cpp, line63, no tgamma
line 86,88 no erf.
my compiler is vs2010, maybe these are contained in newer compilers.

and in torrspar.cpp, line 143
this erf conditional function is not right while xx ==1

and why we need unit_sdf in facet.cpp, line 22, this line will cause init problem.

**Comment by thomas-germer** [comment]
You should remove the functions erf and erfc in torrspar.cpp. The functions erf, erfc, and tgamma are defined in the C99 standard. 

The definition of unit_sdf shouldn't cause init problems, but it is not needed. It is a relic of an old version. It will be removed.

These changes will soon be pushed to github.
